title: High Resolution Isotope Pattern Generation
author: Nick Patikas
email: cs091747@cs.uoi.gr
description: > #
  This page serves a Google Summer of Code blog for the year 2017.
  The project is part of the <a href="https://www.openms.de/"> OpenMS</a> software that is hosted in GSoC by Open Bioinformatics Foundation.
  Updates are posted every week during the coding period. 
  You can find more about the project <a href="https://summerofcode.withgoogle.com/projects/#6438529434386432"> here </a>.

defaults:
  - scope:
      path: "_assets/img"
    values:
      image: true

twitter_username: ou_nikos
github_username:  pati-ni

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
